version: "3.8"
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-config:/etc/gitlab-runner gitlab/gitlab-runner register
    environment:
      - CI_SERVER_URL=https://git.${MASTER_URL}/
      - REGISTRATION_TOKEN=${GITLAB_RUNNER_TOKEN}
    networks:
      - private
    logging:
      driver: none
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_PORT: 2027
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - private
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 600s
    logging:
      driver: none
volumes:
  gitlab-runner-config:
networks:
  private:
    driver: overlay
    external: true
